---
version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.10
  publisher:
    docker:
      - image: quay.io/cloudalchemy/publisher:latest

jobs:
  lint:
    executor: python
    steps:
      - checkout
      - run: pip install ansible ansible-lint yamllint flake8
      - run: ansible-lint
      - run: yamllint .
      - run: flake8

  # splitting up jobs (test_default, test_alternative, test_latest) so that they run in parallel.
  test_default:
    executor: python
    parameters:
      ansible:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install "ansible~=<<parameters.ansible >>.0"
      - run: pip install -r test-requirements.txt
      - run:
          no_output_timeout: 60m
          command: molecule test -s default --destroy always
  test_alternative:
    executor: python
    parameters:
      ansible:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install "ansible~=<<parameters.ansible >>.0"
      - run: pip install -r test-requirements.txt
      - run:
          no_output_timeout: 60m
          command: |
            if [[ -d 'molecule/alternative' ]]; then
              molecule test -s alternative --destroy always
            else
              echo 'No alternative test'
            fi
  test_latest:
    executor: python
    parameters:
      ansible:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install "ansible~=<<parameters.ansible >>.0"
      - run: pip install -r test-requirements.txt
      - run:
          no_output_timeout: 60m
          command: |
            if [[ -z "${CIRCLE_PULL_REQUEST}" ]] && [[ -d 'molecule/latest' ]]; then
              molecule test -s latest --destroy always
            else
              echo 'Not running latest on PR'
            fi
  release:
    executor: publisher
    steps:
      - checkout
      - run: |
          PROJECT_USERNAME="${CIRCLE_PROJECT_USERNAME}" \
          PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME}" \
          create_release

  galaxy:
    executor: python
    steps:
      - checkout
      - run: pip install ansible
      - run: ansible-galaxy role import --token "${GALAXY_TOKEN}" "${CIRCLE_PROJECT_USERNAME}" "${CIRCLE_PROJECT_REPONAME}"

workflows:
  version: 2
  molecule:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test_default:
          matrix:
            parameters:
              ansible:
                - "2.9"
                - "2.10"
                - "4.10"
                - "5.1"
          filters:
            tags:
              only: /.*/
      - test_alternative:
          matrix:
            parameters:
              ansible:
                - "2.9"
                - "2.10"
                - "4.10"
                - "5.1"
          filters:
            tags:
              only: /.*/
      - test_latest:
          matrix:
            parameters:
              ansible:
                - "2.9"
                - "2.10"
                - "4.10"
                - "5.1"
          filters:
            tags:
              only: /.*/
      - release:
          context: release
          requires:
            - lint
            - test_default
            - test_alternative
            - test_latest
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - galaxy:
          context: galaxy
          requires:
            - lint
            - test_default
            - test_alternative
            - test_latest
            - release
          filters:
            branches:
              only: master
